import axios from "axios";
import ButtonCoponent from "./Buttons";
import Button01 from "@/components/etc/Button01";
import { Metadata } from "next";
import Link from "next/link";


export const metadata: Metadata = {
    title: "페이지1",
    description: "Generated by create next app",
};

export default async function about() {
    const res = await axios.get('https://jsonplaceholder.typicode.com/posts');
    console.log(res.data[0])
    console.log(res.data[0].title)
    return (
        <div>
            <h1>
                <ButtonCoponent/>
                <Button01 caption="bt01" bg_color="blue"/>
                <Link href='/'>돌아가기</Link>
            </h1>
        </div>
    );
}
