import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/UI/Nav/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KDT 미니 프로젝트",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col justify-between bg-gradient-to-br from-indigo-50 to-white dark:from-gray-900 dark:to-gray-800 text-gray-900 dark:text-white font-sans">
          <Nav />
          <main className="flex flex-col w-full max-w-5xl mx-auto px-4 sm:px-8 pt-28 pb-20 gap-12">
            {children}
          </main>
          <footer className="text-sm text-gray-500 text-center dark:text-gray-400 mt-16">
            © 2025 WasteSort. All rights reserved.
          </footer>
        </div>
      </body>
    </html>
  );
}
